// Mock data for Counsellor Detail Screens - Muaath (Member 4). Supports FR01, FR05.
// Local mock data for Request Detail, Confirmed Session, Past Sessions, and Notification Detail.

import {
  RequestDetailData,
  ConfirmedSessionData,
  PastSessionItem,
  PastSessionsStats,
  NotificationDetailData,
  PreChatWaitingRoomData,
  ClinicalAlertPreferences,
  PatientItem,
  AnonymousSessionDetailData,
  SessionNotesData,
  ClinicalNoteEntry,
} from "@/types/counsellorDetailScreens";

// ─── Request Detail: Student #5104 ───
export const MOCK_REQUEST_DETAIL: RequestDetailData = {
  id: "req-1",
  studentId: "std-5104",
  studentAnonId: "Student #5104",
  displayName: "Student #5104",
  idMode: "anonymous",
  faculty: "School of Applied Sciences",
  level: "Undergraduate",
  department: "School of Applied Sciences",
  sessionType: "video",
  sessionTypeLabel: "Encrypted Video Call (45m)",
  isEncrypted: true,
  concern: "Academic Pressure & Burnout",
  consultationNumber: "1st consultation with you",
  duration: "45m",
  proposedDate: "Tomorrow, Tuesday, 19 Aug",
  proposedTime: "10:00 AM – 10:45 AM (Local Time)",
  status: "pending",
  moodTrend: [
    { day: "Thu", score: 3.5 },
    { day: "Fri", score: 3.4 },
    { day: "Sat", score: 2.8 },
    { day: "Sun", score: 2.2 },
    { day: "Mon", score: 1.9 },
  ],
  moodBriefLabel: "Mild Stress Dip",
  aiBrief:
    "Student reported elevated stress and sleep disturbances leading into mid-terms over the weekend.",
  personalNote:
    "I've been feeling completely overwhelmed with upcoming finals and having trouble concentrating during lectures. Hoping to learn practical grounding techniques to manage panic spikes before exams.",
  urgencyLevel: "Standard (Nor...",
  format: "Camera On • A...",
  awaitingReplyHours: 2,
};

// ─── Confirmed Session: Student #4021 ───
export const MOCK_CONFIRMED_SESSION: ConfirmedSessionData = {
  id: "session-1",
  studentId: "std-4021",
  studentAnonId: "Student #4021",
  displayName: "Student #4021",
  idMode: "anonymous",
  faculty: "Faculty of Science",
  yearLevel: "Year 2",
  sessionType: "video",
  sessionTypeLabel: "Encrypted Video Consultation",
  isEncrypted: true,
  sessionRef: "#ME-8402",
  date: "Today, Monday, 18 Aug",
  time: "02:00 PM – 02:45 PM",
  roomStatus: "ready",
  startsIn: "25 mins",
  checkInMood: 2.5,
  maxMood: 5.0,
  moodLabel: "Mild strain",
  intakeNote:
    "I've been feeling elevated anxiety ahead of presentations and struggling with sleep disruption over the past week. Looking to review the breathing exercises we discussed and discuss coping mechanisms.",
  tags: ["Academic Stress", "Presentation Anxiety", "Sleep Hygiene"],
  protocolTitle: "Counselor Room Protocol",
  protocolDescription:
    "Ensure private headset is connected. Case notes will auto-encrypt to Student #4021 record immediately post-session.",
};

// ─── Past Sessions History ───
export const MOCK_PAST_SESSIONS_STATS: PastSessionsStats = {
  completedSessions: 48,
  completionRate: 92.3,
  clinicalHours: 36.5,
  verifiedHours: true,
};

export const MOCK_PAST_SESSIONS: PastSessionItem[] = [
  // August 2026
  {
    id: "past-1",
    studentId: "std-4021",
    studentAnonId: "Student #4021",
    displayName: "Student #4021",
    idMode: "anonymous",
    sessionType: "video",
    sessionTypeLabel: "Video Consultation",
    duration: "45 min",
    date: "Fri, 15 Aug",
    time: "02:00 PM",
    concern: "Academic Stress & Exams",
    status: "completed",
    monthGroup: "August 2026",
  },
  {
    id: "past-2",
    studentId: "std-maya",
    studentAnonId: "Student #3189",
    displayName: "Maya Senanayake",
    idMode: "standard",
    sessionType: "chat",
    sessionTypeLabel: "Secured Chat",
    duration: "45 min",
    date: "Wed, 13 Aug",
    time: "11:30 AM",
    concern: "Sleep Routine & Anxiety",
    status: "completed",
    monthGroup: "August 2026",
  },
  {
    id: "past-3",
    studentId: "std-8812",
    studentAnonId: "Student #8812",
    displayName: "Student #8812",
    idMode: "anonymous",
    sessionType: "in-person",
    sessionTypeLabel: "In-Person • Room 302",
    duration: "45 min",
    room: "Room 302",
    date: "Mon, 11 Aug",
    time: "10:00 AM",
    concern: "Social Connection",
    status: "rescheduled",
    monthGroup: "August 2026",
  },
  // July 2026
  {
    id: "past-4",
    studentId: "std-kevin",
    studentAnonId: "Student #7220",
    displayName: "Kevin Thilakarathne",
    idMode: "standard",
    sessionType: "video",
    sessionTypeLabel: "Video Consultation",
    duration: "45 min",
    date: "Thu, 30 Jul",
    time: "03:15 PM",
    concern: "Presentation Anxiety",
    status: "completed",
    monthGroup: "July 2026",
  },
  {
    id: "past-5",
    studentId: "std-3319",
    studentAnonId: "Student #3319",
    displayName: "Student #3319",
    idMode: "anonymous",
    sessionType: "video",
    sessionTypeLabel: "Video Consultation",
    duration: "45 min",
    date: "Tue, 21 Jul",
    time: "09:30 AM",
    concern: "Burnout Recovery",
    status: "pending-wrapup",
    privateNotes:
      "Student demonstrated improved breathing regulation; follow-up on exam pacing strategy and sleep stability schedule recommended.",
    monthGroup: "July 2026",
  },
  {
    id: "past-6",
    studentId: "std-nisali",
    studentAnonId: "Student #2201",
    displayName: "Nisali Perera",
    idMode: "standard",
    sessionType: "chat",
    sessionTypeLabel: "Secured Chat",
    duration: "45 min",
    date: "Fri, 10 Jul",
    time: "04:00 PM",
    concern: "Mid-Term Overwhelm",
    status: "completed",
    monthGroup: "July 2026",
  },
];

// ─── Notification Detail: Student #5104 triage alert ───
export const MOCK_NOTIFICATION_DETAIL: NotificationDetailData = {
  id: "notif-1",
  alertType: "clinical-triage",
  title: "New Session Request: Student #5104",
  studentId: "std-5104",
  studentAnonId: "Student #5104",
  receivedAt: "Today at 09:15 AM",
  triagePriority: "high",
  studentMode: "Anonymous Mode",
  studentLevel: "2nd Year Undergraduate",
  isVerified: true,
  requestType: "45-Minute Intake Consultation",
  modality: "Video Consultation (End-to-End Encrypted)",
  proposedDate: "Tomorrow, Wednesday",
  proposedTime: "02:00 PM – 02:45 PM",
  primaryConcern:
    "Acute exam stress, difficulty sleeping, submitted PHQ-9.",
  phqScore: 14,
  phqRange: "MODERATE RANGE",
  actions: {
    primary: "Review & Accept",
    secondary: "Suggest Alternative",
    tertiary: "Decline",
  },
};

// ─── Pre-Chat Waiting Room: Student #4021 ───
export const MOCK_PRE_CHAT_WAITING_ROOM: PreChatWaitingRoomData = {
  studentId: "std-4021",
  studentAnonId: "Student #4021",
  scheduledTime: "Today, 11:00 AM",
  intakeRoomStatus: "Today, Monday 18 Aug • Intake Room Ready",
  phqScore: 14,
  primaryConcern: "Exam Stress & Insomnia",
  duration: "45 minutes",
  sharedContext:
    "Feeling overwhelmed with upcoming mid-term finals and having trouble concentrating.",
  openingPrompts: [
    {
      id: "prompt-1",
      iconName: "hand-left-outline",
      promptText: "Hello! Welcome to your session. How are you feeling today?",
    },
    {
      id: "prompt-2",
      iconName: "leaf-outline",
      promptText:
        "Hi there. I reviewed your check-in note regarding exam stress. Would you like to start there?",
    },
    {
      id: "prompt-3",
      iconName: "time-outline",
      promptText:
        "Welcome. We have 45 minutes today—take your time settling in.",
    },
  ],
};

// ─── Clinical Alerts & Preferences ───
export const DEFAULT_CLINICAL_ALERT_PREFERENCES: ClinicalAlertPreferences = {
  crisisRiskTriggers: true,
  newAppointmentRequests: true,
  upcomingSessionReminders: true,
  intakeFormSubmissions: true,
  secureChatMessages: true,
  quietHoursDutyOff: true,
  advanceReminderMinutes: 15,
  advanceReminderType: "gentle",
  scheduledWindow: "06:00 PM – 08:00 AM",
  previewStudentIdentityHidden: true,
  priorityOverrideAlwaysOn: true,
};

// ─── Patients Directory List (24 assigned cases representation) ───
export const MOCK_PATIENTS_LIST: PatientItem[] = [
  {
    id: "pat-1",
    studentId: "std-4810",
    studentAnonId: "Student #4810",
    displayName: "Sarah Jenkins",
    idMode: "standard",
    initials: "SJ",
    badgeText: "WEEKLY",
    badgeStyle: "mint",
    sessionTimingText: "Next: Tomorrow, 10:00 AM • Last: 3 days ago",
    isActive: true,
    hasUnread: false,
    status: "active",
    totalLogs: 8,
    lastSessionDate: "3 days ago",
  },
  {
    id: "pat-2",
    studentId: "std-5104",
    studentAnonId: "Student #5104",
    displayName: "Student #5104",
    idMode: "anonymous",
    avatarIcon: "shield",
    badgeText: "ANONYMOUS",
    badgeStyle: "slate",
    sessionTimingText: "New — 1st consultation • Today, 2:30 PM",
    isActive: true,
    hasUnread: true,
    status: "active",
    totalLogs: 1,
    lastSessionDate: "Today",
  },
  {
    id: "pat-3",
    studentId: "std-3902",
    studentAnonId: "Student #3902",
    displayName: "Alex Rivera",
    idMode: "standard",
    initials: "AR",
    badgeText: "BI-WEEKLY",
    badgeStyle: "amber",
    sessionTimingText: "Last session: Oct 12 • 4 completed logs",
    isActive: false,
    hasUnread: false,
    status: "active",
    totalLogs: 4,
    lastSessionDate: "Oct 12",
  },
  {
    id: "pat-4",
    studentId: "std-8821",
    studentAnonId: "Student #8821",
    displayName: "Student #8821",
    idMode: "anonymous",
    avatarIcon: "key",
    badgeText: "ANONYMOUS",
    badgeStyle: "slate",
    sessionTimingText: "Follow-up pending • Note submitted 4h ago",
    isActive: false,
    hasUnread: true,
    status: "pending",
    totalLogs: 3,
    lastSessionDate: "Oct 14",
  },
  {
    id: "pat-5",
    studentId: "std-6291",
    studentAnonId: "Student #6291",
    displayName: "Maya Lin",
    idMode: "standard",
    initials: "ML",
    badgeText: "WEEKLY",
    badgeStyle: "teal",
    sessionTimingText: "Next: Friday, 9:00 AM • Wellness Plan v2",
    isActive: false,
    hasUnread: false,
    status: "active",
    totalLogs: 6,
    lastSessionDate: "Oct 10",
  },
  {
    id: "pat-6",
    studentId: "std-7712",
    studentAnonId: "Student #7712",
    displayName: "David Chen",
    idMode: "standard",
    initials: "DC",
    badgeText: "MONTHLY",
    badgeStyle: "indigo",
    sessionTimingText: "Last session: 12 days ago • Review scheduled",
    isActive: false,
    hasUnread: false,
    status: "active",
    totalLogs: 2,
    lastSessionDate: "12 days ago",
  },
  {
    id: "pat-7",
    studentId: "std-3419",
    studentAnonId: "Student #3419",
    displayName: "Student #3419",
    idMode: "anonymous",
    avatarIcon: "lock",
    badgeText: "ANONYMOUS",
    badgeStyle: "slate",
    sessionTimingText: "Consult completed Oct 04 • Inactive",
    isActive: false,
    hasUnread: false,
    status: "inactive",
    totalLogs: 5,
    lastSessionDate: "Oct 04",
  },
];

// ─── Anonymous Session Details: Student #8812 ───
export const MOCK_ANONYMOUS_SESSION_8812: AnonymousSessionDetailData = {
  id: "session-3",
  studentId: "std-8812",
  studentAnonId: "Student #8812",
  displayName: "Student #8812",
  idMode: "anonymous",
  sessionType: "in-person",
  sessionTypeLabel: "In-Person Consultation",
  location: "Room 302, Counseling Wing",
  locationSub: "Main Clinical Building, 3rd Floor",
  timeRange: "02:30 PM – 03:15 PM",
  duration: "45 min",
  timeRelative: "In 5h 15m",
  caseRef: "#ME-8812",
  recurrence: "Bi-weekly Ongoing",
  intakeType: "Single Intake",
  concernTags: ["Academic Pressure", "Social Connection"],
  bookingStatus: "Clinically Verified",
  privacyNotice: "Anonymous — student ID withheld",
  complianceNotice: "FERPA & HIPAA Encrypted Case Record",
  prepNotes:
    "Student indicated elevated tension regarding upcoming presentation schedules and social transition fatigue. Review somatic breathing grounding tools and evaluate routine balance from previous intake note.",
  prepNoteUpdatedAt: "Updated 3h ago",
  isCheckedIn: false,
};

// ─── Session Notes: Maya Senanayake ───
export const MOCK_SESSION_NOTES_MAYA: SessionNotesData = {
  studentId: "std-maya",
  studentAnonId: "Student #3189",
  displayName: "Maya Senanayake",
  idMode: "standard",
  sessionType: "chat",
  sessionTypeLabel: "Secured Chat Session",
  timeRelative: "In 2h 15m",
  timeRange: "11:30 AM – 12:15 PM",
  duration: "45 min",
  caseRef: "#ME-4402",
  sessionOrdinal: "3rd Follow-up Session",
  followUpPriority: "Priority Review",
  followUpAction:
    "Sleep hygiene & journaling routine review. Evaluate adherence to morning sunlight exposure and thought-reframing worksheets.",
  topics: [
    { icon: "🌙", name: "Sleep Hygiene" },
    { icon: "📓", name: "Journaling Routine" },
    { icon: "⚡", name: "Academic Anxiety" },
    { icon: "🧠", name: "Cognitive Reframing" },
  ],
  notes: [
    {
      id: "note-1",
      date: "Aug 11, 2026 • Chat",
      modality: "Chat",
      status: "Completed",
      content:
        "Student reports average sleep latency improved from 75 mins to 35 mins following evening digital curfew. Still experiencing anticipatory panic during Sunday revision blocks. Introduced 4-7-8 breathing practice and structured journaling prompt.",
      counselorName: "Dr. Anjali Perera",
      signedStatus: "Signed & Synced",
    },
    {
      id: "note-2",
      date: "Aug 4, 2026 • Initial Follow-up",
      modality: "Initial Follow-up",
      status: "Completed",
      content:
        "Reviewed baseline sleep logs. Identified ruminative loop triggered around 11:30 PM. Recommended physical notebook rather than mobile notes app for worry dump. Patient receptivity high.",
      counselorName: "Dr. Anjali Perera",
      signedStatus: "Signed & Synced",
    },
  ],
};

// ─── Quick Select Students for Add Session ───
export const MOCK_ADD_SESSION_STUDENTS = [
  {
    id: "std-5104",
    studentAnonId: "Student #5104",
    displayName: "Student #5104 (Anonymous)",
    idMode: "anonymous" as const,
    quickLabel: "#5104 (Anon)",
  },
  {
    id: "std-sarah",
    studentAnonId: "Student #4820",
    displayName: "Sarah Jenkins",
    idMode: "standard" as const,
    quickLabel: "Sarah Jenkins",
  },
  {
    id: "std-alex",
    studentAnonId: "Student #6291",
    displayName: "Alex Rivera",
    idMode: "standard" as const,
    quickLabel: "Alex Rivera",
  },
];

